import type { BoardLayout, BoardSpaceDefinition } from './types.js';

export const ADIPOLY_BOARD_SPACES: BoardSpaceDefinition[] = [
  {
    id: 'space_0',
    index: 0,
    name: 'Genesis Square',
    type: 'START',
    description: 'Collect ₹200 bonus when passing or landing.',
  },
  {
    id: 'space_1',
    index: 1,
    name: 'Startup Alley',
    type: 'PROPERTY',
    group: 'Incubation',
    groupColor: '#78350F',
    price: 60,
    baseRent: 6,
  },
  {
    id: 'space_2',
    index: 2,
    name: 'Market Pulse',
    type: 'EVENT',
    description: 'Draw an original ADIPOLY event card.',
  },
  {
    id: 'space_3',
    index: 3,
    name: "Founder's Row",
    type: 'PROPERTY',
    group: 'Incubation',
    groupColor: '#78350F',
    price: 80,
    baseRent: 8,
  },
  {
    id: 'space_4',
    index: 4,
    name: 'Tax Audit Bureau',
    type: 'SPECIAL',
    description: 'Regulatory audit: pay 10% cash assessment.',
  },
  {
    id: 'space_5',
    index: 5,
    name: 'Hyperloop Freight',
    type: 'PROPERTY',
    group: 'Logistics',
    groupColor: '#06B6D4',
    price: 200,
    baseRent: 25,
  },
  {
    id: 'space_6',
    index: 6,
    name: 'Silicon Strip',
    type: 'PROPERTY',
    group: 'Computing',
    groupColor: '#38BDF8',
    price: 100,
    baseRent: 10,
  },
  {
    id: 'space_7',
    index: 7,
    name: 'Cyber Vault',
    type: 'PROPERTY',
    group: 'Computing',
    groupColor: '#38BDF8',
    price: 120,
    baseRent: 12,
  },
  {
    id: 'space_8',
    index: 8,
    name: 'Regulatory Detention',
    type: 'JAIL',
    description: 'Just visiting or serving detention penalty.',
  },
  {
    id: 'space_9',
    index: 9,
    name: 'Biotech Lab',
    type: 'PROPERTY',
    group: 'BioTech',
    groupColor: '#A855F7',
    price: 140,
    baseRent: 14,
  },
  {
    id: 'space_10',
    index: 10,
    name: 'Market Pulse',
    type: 'EVENT',
    description: 'Draw an original ADIPOLY event card.',
  },
  {
    id: 'space_11',
    index: 11,
    name: 'Nano Synthesis',
    type: 'PROPERTY',
    group: 'BioTech',
    groupColor: '#A855F7',
    price: 160,
    baseRent: 16,
  },
  {
    id: 'space_12',
    index: 12,
    name: 'Exchange Floor',
    type: 'AUCTION',
    description: 'Public trading hall: initiates property bidding rounds.',
  },
  {
    id: 'space_13',
    index: 13,
    name: 'Aero Cargo',
    type: 'PROPERTY',
    group: 'Logistics',
    groupColor: '#06B6D4',
    price: 200,
    baseRent: 25,
  },
  {
    id: 'space_14',
    index: 14,
    name: 'Solar Grid',
    type: 'PROPERTY',
    group: 'Clean Energy',
    groupColor: '#F97316',
    price: 180,
    baseRent: 18,
  },
  {
    id: 'space_15',
    index: 15,
    name: 'Fusion Station',
    type: 'PROPERTY',
    group: 'Clean Energy',
    groupColor: '#F97316',
    price: 200,
    baseRent: 20,
  },
  {
    id: 'space_16',
    index: 16,
    name: 'Venture Dividend',
    type: 'BONUS',
    description: 'Yield payout: collect 5% cash return.',
  },
  {
    id: 'space_17',
    index: 17,
    name: 'Cloud Corridor',
    type: 'PROPERTY',
    group: 'Cloud Tech',
    groupColor: '#EC4899',
    price: 220,
    baseRent: 22,
  },
  {
    id: 'space_18',
    index: 18,
    name: 'Market Pulse',
    type: 'EVENT',
    description: 'Draw an original ADIPOLY event card.',
  },
  {
    id: 'space_19',
    index: 19,
    name: 'Quantum Datacenter',
    type: 'PROPERTY',
    group: 'Cloud Tech',
    groupColor: '#EC4899',
    price: 240,
    baseRent: 24,
  },
  {
    id: 'space_20',
    index: 20,
    name: 'Gov Innovation Grant',
    type: 'BONUS',
    description: 'Receive public R&D grant of ₹150.',
  },
  {
    id: 'space_21',
    index: 21,
    name: 'Orbital Spaceport',
    type: 'PROPERTY',
    group: 'Logistics',
    groupColor: '#06B6D4',
    price: 200,
    baseRent: 25,
  },
  {
    id: 'space_22',
    index: 22,
    name: 'Media Syndicate',
    type: 'PROPERTY',
    group: 'Media',
    groupColor: '#EAB308',
    price: 260,
    baseRent: 26,
  },
  {
    id: 'space_23',
    index: 23,
    name: 'Broadcast Tower',
    type: 'PROPERTY',
    group: 'Media',
    groupColor: '#EAB308',
    price: 280,
    baseRent: 28,
  },
  {
    id: 'space_24',
    index: 24,
    name: 'Regulatory Raid',
    type: 'SPECIAL',
    description: 'Direct order: proceed immediately to Detention.',
  },
  {
    id: 'space_25',
    index: 25,
    name: 'AI Foundry',
    type: 'PROPERTY',
    group: 'Artificial Intelligence',
    groupColor: '#10B981',
    price: 300,
    baseRent: 30,
  },
  {
    id: 'space_26',
    index: 26,
    name: 'Neural Grid',
    type: 'PROPERTY',
    group: 'Artificial Intelligence',
    groupColor: '#10B981',
    price: 320,
    baseRent: 32,
  },
  {
    id: 'space_27',
    index: 27,
    name: 'Market Pulse',
    type: 'EVENT',
    description: 'Draw an original ADIPOLY event card.',
  },
  {
    id: 'space_28',
    index: 28,
    name: 'Deep Sea Cable',
    type: 'PROPERTY',
    group: 'Logistics',
    groupColor: '#06B6D4',
    price: 200,
    baseRent: 25,
  },
  {
    id: 'space_29',
    index: 29,
    name: 'Sovereign Wealth',
    type: 'PROPERTY',
    group: 'Apex Capital',
    groupColor: '#1E40AF',
    price: 350,
    baseRent: 35,
  },
  {
    id: 'space_30',
    index: 30,
    name: 'High Risk Hedge',
    type: 'SPECIAL',
    description: 'Roll single die: 1-3 lose ₹100, 4-6 win ₹250.',
  },
  {
    id: 'space_31',
    index: 31,
    name: 'Apex Tower',
    type: 'PROPERTY',
    group: 'Apex Capital',
    groupColor: '#1E40AF',
    price: 400,
    baseRent: 50,
  },
];

export const DEFAULT_BOARD_LAYOUT: BoardLayout = {
  totalSpaces: ADIPOLY_BOARD_SPACES.length,
  spaces: ADIPOLY_BOARD_SPACES,
};
